export const RACER_BADGES = ['PK','WH','AP','DV','AI','DH','CH','JT'];

const icon = (body, accent = '#22c55e') => `<svg viewBox="0 0 64 64" aria-hidden="true" focusable="false"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff"/><stop offset="1" stop-color="${accent}"/></linearGradient></defs>${body}</svg>`;

export const ITEM_DEFS = [
  {id:'candle',name:'GREEN CANDLE',short:'CANDLE',accent:'#43f47a',icon:icon('<path d="M14 49h38v6H14z" fill="#0b2d18"/><path d="M20 42l9-11 8 6 12-19" fill="none" stroke="url(#g)" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M40 18h9v9" fill="none" stroke="#0b2d18" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>','#43f47a')},
  {id:'rocket',name:'PUMP ROCKET',short:'ROCKET',accent:'#ff9f43',icon:icon('<path d="M38 10c8 2 14 8 16 16L37 43 21 27z" fill="url(#g)" stroke="#0b2d18" stroke-width="4"/><circle cx="39" cy="25" r="5" fill="#0b2d18"/><path d="M22 31l-8 3 7 7m10-4-3 13 9-8" fill="#ff6a3d" stroke="#0b2d18" stroke-width="4" stroke-linejoin="round"/><path d="M18 44l-8 9m16-7-5 9" stroke="#ffe45f" stroke-width="5" stroke-linecap="round"/>','#ff9f43')},
  {id:'diamond',name:'DIAMOND HANDS',short:'SHIELD',accent:'#58dcff',icon:icon('<path d="M12 25l9-13h22l9 13-20 28z" fill="url(#g)" stroke="#0b2d18" stroke-width="4" stroke-linejoin="round"/><path d="M12 25h40M21 12l11 13 11-13M32 25v28" fill="none" stroke="#0b2d18" stroke-width="3"/>','#58dcff')},
  {id:'rug',name:'RUG PULL',short:'RUG',accent:'#ff5964',icon:icon('<path d="M12 18h40v28H12z" fill="url(#g)" stroke="#0b2d18" stroke-width="4"/><path d="M18 24l9 8-9 8m28-16-9 8 9 8M12 50h40" fill="none" stroke="#0b2d18" stroke-width="4" stroke-linecap="round"/><path d="M16 48v7m8-7v7m16-7v7m8-7v7" stroke="#ff5964" stroke-width="3"/>','#ff5964')},
  {id:'mev',name:'MEV ZAP',short:'ZAP',accent:'#bf7cff',icon:icon('<path d="M34 7L15 35h14l-2 22 22-31H35z" fill="url(#g)" stroke="#0b2d18" stroke-width="4" stroke-linejoin="round"/><circle cx="13" cy="14" r="5" fill="#bf7cff"/><circle cx="51" cy="49" r="5" fill="#58dcff"/>','#bf7cff')},
  {id:'airdrop',name:'AIRDROP',short:'DROP',accent:'#ffd84d',icon:icon('<path d="M14 24c2-11 10-17 18-17s16 6 18 17l-18 9z" fill="url(#g)" stroke="#0b2d18" stroke-width="4"/><path d="M16 25l10 15m22-15L38 40M32 32v8" stroke="#0b2d18" stroke-width="3"/><rect x="23" y="39" width="18" height="16" rx="3" fill="#ffd84d" stroke="#0b2d18" stroke-width="4"/>','#ffd84d')}
];

export function createMicroFX(THREE, scene, {reducedMotion = false} = {}) {
  const mobile=globalThis.innerWidth<700;
  const dummy=new THREE.Object3D(),zero=new THREE.Matrix4().makeScale(0,0,0),forwardAxis=new THREE.Vector3(0,0,1),tint=new THREE.Color();
  const makePool=(geometry,size,opacity=.88)=>{
    const material=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false});
    const mesh=new THREE.InstancedMesh(geometry,material,size);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;mesh.renderOrder=8;
    const states=Array.from({length:size},()=>({life:0,max:1,pos:new THREE.Vector3(),vel:new THREE.Vector3(),rot:new THREE.Euler(),spin:new THREE.Vector3(),color:new THREE.Color(),scale:0,expand:0,gravity:0,quat:null}));
    for(let i=0;i<size;i++){mesh.setMatrixAt(i,zero);mesh.setColorAt(i,new THREE.Color(0x000000))}mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true;scene.add(mesh);
    let cursor=0;
    const spawn=(data)=>{const i=cursor++%size,s=states[i];s.life=s.max=data.life||.5;s.pos.copy(data.pos);if(data.vel)s.vel.copy(data.vel);else s.vel.copy(forwardAxis).multiplyScalar(data.speed||0);s.rot.set(Math.random()*3,Math.random()*3,Math.random()*3);s.spin.set((Math.random()-.5)*7,(Math.random()-.5)*7,(Math.random()-.5)*7);s.color.set(data.color||0xffffff);s.scale=data.scale||1;s.expand=data.expand||0;s.gravity=data.gravity||0;s.quat=data.quat?.clone?.()||null;return s};
    const update=(dt)=>{for(let i=0;i<size;i++){const s=states[i];if(s.life<=0){mesh.setMatrixAt(i,zero);continue}s.life-=dt;if(s.life<=0){mesh.setMatrixAt(i,zero);continue}s.pos.addScaledVector(s.vel,dt);s.vel.y-=s.gravity*dt;s.rot.x+=s.spin.x*dt;s.rot.y+=s.spin.y*dt;s.rot.z+=s.spin.z*dt;const fade=Math.max(0,s.life/s.max),k=Math.max(.001,(s.scale+s.expand*(1-fade))*Math.min(1,fade*2.4));dummy.position.copy(s.pos);dummy.rotation.copy(s.rot);dummy.scale.setScalar(k);if(s.quat)dummy.quaternion.copy(s.quat);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,tint.copy(s.color).multiplyScalar(.3+.7*fade))}mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true};
    return{spawn,update,states,mesh};
  };
  const sparks=makePool(new THREE.OctahedronGeometry(.2,0),reducedMotion?18:mobile?28:42,.9);
  const streaks=makePool(new THREE.BoxGeometry(.1,.1,1.25),reducedMotion?6:mobile?10:16,.82);
  const rings=makePool(new THREE.TorusGeometry(1,.075,5,22),reducedMotion?4:8,.78);
  const spawnBurst=(origin,color=0x6dff8a,count=10,power=1)=>{const total=Math.min(reducedMotion?Math.ceil(count*.35):count,mobile?12:18);for(let i=0;i<total;i++){const a=Math.random()*Math.PI*2,speed=(2.5+Math.random()*5)*power;sparks.spawn({pos:origin.clone().add(new THREE.Vector3((Math.random()-.5)*.8,.35+Math.random(),(Math.random()-.5)*.8)),vel:new THREE.Vector3(Math.cos(a)*speed,2+Math.random()*5*power,Math.sin(a)*speed),life:.36+Math.random()*.34,scale:.55+Math.random()*.6,gravity:10,color:i%5?color:0xffffff})}};
  const spawnRing=(origin,color=0x6dff8a,scale=.7,life=.45)=>rings.spawn({pos:origin,life,scale,expand:3.2*scale,color,quat:new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2)});
  function pickup(origin){spawnBurst(origin,0x69ff8c,14,.85);spawnRing(origin,0xffffff,.85,.34);spawnRing(origin,0x5aff83,.5,.46);const total=reducedMotion?2:mobile?3:5;for(let n=0;n<total;n++)streaks.spawn({pos:origin.clone().add(new THREE.Vector3((Math.random()-.5)*1.4,.3+Math.random(),(Math.random()-.5)*1.4)),vel:new THREE.Vector3((Math.random()-.5)*2,7+Math.random()*6,(Math.random()-.5)*2),life:.26+Math.random()*.18,scale:.8+Math.random(),color:n%3?0x67ff8b:0xffffff})}
  function respawn(origin){spawnRing(origin,0x6eff91,.35,.5);spawnBurst(origin,0xffffff,5,.35)}
  function boost(origin,forward=new THREE.Vector3(0,0,1),strength=1){spawnRing(origin,0xffec70,.5,.28);spawnBurst(origin,0x6dff8e,Math.round(6*strength),.45);const dir=forward.clone().normalize(),quat=new THREE.Quaternion().setFromUnitVectors(forwardAxis,dir);for(let i=0;i<(reducedMotion?2:4);i++)streaks.spawn({pos:origin.clone().add(new THREE.Vector3((Math.random()-.5)*2,Math.random(),(Math.random()-.5)*2)),vel:dir.clone().multiplyScalar(-8-Math.random()*7),life:.2+Math.random()*.16,scale:.6+Math.random(),color:i%3?0x66ff88:0xffef73,quat})}
  function drift(origin,charge=0){spawnBurst(origin,charge>.9?0xffd84d:0x63e9ff,reducedMotion?1:2,.25+.18*charge)}
  function trail(origin,color=0x72ff84){sparks.spawn({pos:origin.clone().add(new THREE.Vector3((Math.random()-.5)*.7,.25+Math.random()*.45,(Math.random()-.5)*.7)),vel:new THREE.Vector3((Math.random()-.5)*.8,.5+Math.random(),(Math.random()-.5)*.8),life:.24+Math.random()*.18,scale:.38+Math.random()*.25,color})}
  function impact(origin){spawnBurst(origin,0xffd966,9,.75);spawnRing(origin,0xffffff,.4,.26)}
  function itemUse(id,origin,forward=new THREE.Vector3(0,0,1)){const colors={candle:0x52ff7d,rocket:0xff8c42,diamond:0x62dcff,rug:0xff5360,mev:0xbb72ff,airdrop:0xffdb55},color=colors[id]||0xffffff;if(id==='rocket')boost(origin,forward,1.35);else if(id==='mev'){spawnBurst(origin,color,10,.9);spawnRing(origin,0x6be7ff,.55,.32)}else if(id==='diamond'){spawnRing(origin,color,.65,.55);spawnRing(origin,0xffffff,.4,.42)}else if(id==='rug'){spawnBurst(origin,color,12,.8);spawnRing(origin,color,.55,.38)}else if(id==='airdrop'){spawnBurst(origin,color,10,.65);spawnRing(origin,0xffffff,.7,.45)}else boost(origin,forward,1)}
  function celebration(origin,color=0xffdf59){for(let n=0;n<3;n++)setTimeout(()=>{spawnBurst(origin,color,10,.8);spawnRing(origin,n%2?0x62ff85:0xffffff,.5+n*.12,.42)},n*120)}
  function update(dt){const safeDt=Math.min(.05,Math.max(0,dt));sparks.update(safeDt);streaks.update(safeDt);rings.update(safeDt)}
  return{pickup,respawn,boost,drift,trail,impact,itemUse,celebration,update,get count(){let n=0;for(const pool of[sparks,streaks,rings])for(const s of pool.states)if(s.life>0)n++;return n},get drawCalls(){return 3}};
}
